services:
  zensical:
    image: zensical/zensical:latest
    container_name: zensical_docs
    # Par défaut, on veut que ça lance le serveur
    command: serve --dev-addr=0.0.0.0:8000
    volumes:
      # C'est ici que la magie opère : ton dossier actuel devient le dossier /docs
      - ./:/docs
    ports:
      - "8000:8000"
    restart: unless-stopped
