name: Déploiement GitHub Pages

on:
  push:
    branches: ["main"] # Se déclenche lors d'un push sur la branche main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de GitHub Pages
        uses: actions/configure-pages@v4

      - name: Téléchargement de l'artefact
        uses: actions/upload-pages-artifact@v3
        with:
          # Indiquez le dossier contenant vos fichiers (ex: "dist" ou "." pour la racine)
          path: 'site/'

      - name: Déploiement final
        uses: actions/deploy-pages@v4